"""empty message

Revision ID: 118167236f3b
Revises: 7d5c86291130
Create Date: 2020-01-06 15:19:50.325769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118167236f3b'
down_revision = '7d5c86291130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
