"""empty message

Revision ID: 9a9e1b8507f8
Revises: 81c5e38f5196
Create Date: 2019-12-28 12:59:43.565874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9e1b8507f8'
down_revision = '81c5e38f5196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.String(length=120), nullable=True))
    op.add_column('Show', sa.Column('artist_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###
